#+TITLE: Lee Metrics
#+OPTIONS: ^:nil

* Introduction

=lee_metrics= is a modern metrics library for Erlang.
It follows a schema-based approach where all metrics provided by the
applications are listed in the schema.

Built-in metric types (such as counter and gauge) are very lightweight
(having roughly the same overhead as =counter= and =atomics= modules
from Erlang standard library) and are safe to use in hot loops.

* Features

- Metrics schema used to define properties of metrics (such as
  histogram bucket boundaries or gauge aggregation method), to verify
  consistency of metrics data and definitions, and as a source of
  truth for generating documentation.

- Performance and fault safety. Business applications own the metrics,
  rather than the =lee_metrics= application. Business logic can pass
  metrics in variables, there's no additional lookup step. Even if the
  metric is unregistered from =lee_metrics= application, it doesn't
  lead to exceptions in the business code.

- Common Erlang VM metrics are collected by default.

- Metrics schema can be expanded in the runtime.

* Metric types

- =counter_metric= - a scalar monotonically increasing counter implemented using =counters= module.
- =external_counter_metric= - a scalar counter collected via callback.
- =gauge_metric= - a scalar gauge implemented using =atomics= module.
- =external_gauge_metric= - a scalar gauge collected via callback.
- =histogram_metric= - histogram metric.
- =summary_metric= - a metric that keeps number of samples and their sum
- =external_histogram_metric=
- =derivative_metric= - reports first derivative (rate) of a given metric.
